maintainer       'Heavy Water Ops, LLC'
maintainer_email 'support@hw-ops.com'
license          'Apache-2.0'
description      'Deploy chef-handler-users chef report handler'
version          '1.1.0'
name             'chef_handler_users'
